import type { Metadata } from "next";
import { Instrument_Sans, Montserrat, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/navbar/Navbar";
import Footer from "./components/layout/Footer";
import { FAQ } from "../components/sections/Home/FAQ";
import { Analytics } from "@vercel/analytics/next";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const montserrat = Raleway({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSans.variable} ${montserrat.variable} antialiased`}
      >
        <Navbar />
        <main className="pt-[55px] pb-20">{children}</main>
        <FAQ />
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
