import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Instrument_Sans,
  Montserrat,
} from "next/font/google";
import "./globals.css";
import Navbar from "./components/sections/Home/Navbar";
import Footer from "./components/sections/Home/Footer";
import { FAQ } from "./components/sections/Home/FAQ";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${instrumentSans.variable} ${montserrat.variable} antialiased`}
      >
        <Navbar />
        <main className="pt-[55px] pb-20">{children}</main>
        <FAQ />
        <Footer />
      </body>
    </html>
  );
}
